---
- name: "Install Chrony"
  ansible.builtin.package:
    name: chrony
    state: present
    update_cache: true
    cache_valid_time: "{{ '3600' if ansible_facts.pkg_mgr == 'apt' else omit }}"
  become: true

- name: "Configuring Chrony"
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ chrony_config }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart {{ chrony_service }}
